# Generated by Django 5.0.6 on 2024-06-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players_lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["player_list__title", "name"]},
        ),
    ]
